### ISSUE TITLE
Support for landscape orientation

### ISSUE THREAD

**Issue by jean-t86** [chornerman/Surveys#11]
At the moment, the app is forced into portrait mode.

Let's modify this to also support landscape mode for all screens.

**Comment by chornerman** [comment]
Fixed accordingly, but there is still some issue in the above commit. When I rotate screen while fetching data, the old fetching job is still doing its work even after the screen has been rotated. I will try to fix this soon.

**Comment by chornerman** [comment]
Fixed using viewmodel.
