### ISSUE TITLE
Increase unit test coverage for both SurveyUtils and TokenUtils

### ISSUE THREAD

**Issue by jean-t86** [chornerman/Surveys#12]
In particular, `SurveyUtils.getSurveyList`. 

I am curious about the following scenario:

Let's imagine we receive `Constants.unauthorized_error_code` as response code.
The app will retry twice (`if (fetchingCount <= 2)`). 
Let's imagine both times also return `Constants.unauthorized_error_code` as response code.
What happens when `fetchingCount == 3`?

Let's write a unit test to cover this case.

Also, as mentioned in the title, let's increase the code coverage for both `SurveyUtils` and `TokenUtils`.

**Comment by chornerman** [comment]
I have done adding some test cases in both 'SurveyUtilsTest' and 'TokenUtilsTest', but there is an issue that makes retrofit callback not trigger properly. I will try fixing it soon.

**Comment by chornerman** [comment]
Fixed!
