### ISSUE TITLE
Greeting and starting the reviewing process

### ISSUE THREAD

**Issue by jean-t86** [chornerman/Surveys#3]
Hello Chorn @chornerman,

Nice to e-meet you 👋and thanks for your effort on this submission. My name is Jean - an Android Developer at Nimble and I would like to conduct the feedback via Issue tickets regarding your performance here. 

Keep in mind, this is a bidirectional process, so we would love to hear back from you as well, so please don’t hesitate to raise your question/correction in case we missed anything. 

If we’re aligned on any issue here and you’d like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up those fixes 😇

The first issue I would like to see solved is the use of the not-null assertion operator (`!!`). I saw it being used in a few places where the calling object is nullable. Let's try and deal with those as nullable instead.

I hope you find the process enjoyable. Good luck and happy coding 🤘

**Comment by chornerman** [comment]
Hello, and nice to meet you too sir.

The first issue has been solved according to your advice.

If you think this issue is still there or should be solved using another way please tell me.

Thanks you.

**Comment by jean-t86** [comment]
Good morning @chornerman,

Have you pushed the code to your repository yet? 

I can't seem to find the changes.

**Comment by chornerman** [comment]
Sorry for the late response, and sorry about this messy repository. I have to admit here I never did this kind of thing before. And yes, I pushed the code for the closed issues already. It's all staying in the `issue_solving` branch. You can look through the commit history for what commit fix what issue.

If you have any recommendations, please lets me know, and sorry again for the inconvenience.
