### ISSUE TITLE
Basic comments that provide little value

### ISSUE THREAD

**Issue by jean-t86** [chornerman/Surveys#4]
There are a few comments per class. 

Most of them serve no purpose, e.g. 
```
// Survey list adapter
class SurveyRecyclerAdapter(private val items: List<Survey>) :
    RecyclerView.Adapter<SurveyRecyclerAdapter.ViewHolder>() {
...
}
```

Let's get rid of basic comments.

**Comment by chornerman** [comment]
This issue has been solved according to your advice.
If you think this issue is still there or should be solved using another way please tell me.
Thank you.
